# Generated by Django 2.2.5 on 2021-07-25 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='information',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('factor', models.CharField(max_length=64)),
                ('cell_line', models.CharField(max_length=500)),
                ('ucsc', models.CharField(max_length=64)),
                ('lab', models.CharField(max_length=500)),
            ],
        ),
    ]
